lab4
yaaarslv/M34051_3 pull request #4
Opened 2024-10-13 15:41 UTC by yaaarslv

2024-10-14 21:33 UTC, vekajp requested changes

2024-10-14 21:33 UTC, vekajp commented on lab4.md
> +
Допишите требования, отвечая на вопросы так, как вам это будет проще

2024-10-14 21:33 UTC, vekajp commented on lab4.md
> +| Изменение порядка статусов                           | Project. Инвариант: Порядок статусов должен оставаться валидным и не нарушать логику отображения. Согласованность: конечная | Status Managemen
тут нужно проанализировать все изменяющие операции из работы 1

2024-10-14 21:33 UTC, vekajp commented on lab4.md
> +| Status                | ID: UUID, name: String, color: String                                                              | Содержит информацию о статусах задач       | Status Management        |
задача не агрегат?

2024-10-19 15:40 UTC, yaaarslv commented on lab4.md
> +| Status                | ID: UUID, name: String, color: String                                                              | Содержит информацию о статусах задач       | Status Management        |
исправили

2024-10-19 16:03 UTC, Fleack commented on lab4.md
> +
авыавы

2024-10-19 16:06 UTC, Fleack commented on lab4.md
> +| Изменение порядка статусов                           | Project. Инвариант: Порядок статусов должен оставаться валидным и не нарушать логику отображения. Согласованность: конечная | Status Managemen
Не поняли, что за "изменяющие операции", в работе 1 такого нет..

2024-11-17 19:29 UTC, merged